apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vl3j51e0k-python 
  janus-idp.io/tekton: vl3j51e0k-python
  backstage.io/kubernetes-id: vl3j51e0k-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vl3j51e0k-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  